server:
  port: 8081

spring:
  application:
    name: jpa-demo-project
  datasource:
    url: jdbc:mysql://localhost:3306/jpa-demo-project?allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true